// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy3Omly_AwtJJNhqtLlzQEVWo8uClSU-Y',
    appId: '1:230754350559:web:31226696603f71ea02c06a',
    messagingSenderId: '230754350559',
    projectId: 'tempus-fcd8f',
    authDomain: 'tempus-fcd8f.firebaseapp.com',
    storageBucket: 'tempus-fcd8f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApMMhm6mANXN3yg9eli9ZmlOyouKDWhFE',
    appId: '1:230754350559:android:b40f447059f0a10902c06a',
    messagingSenderId: '230754350559',
    projectId: 'tempus-fcd8f',
    storageBucket: 'tempus-fcd8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnqXRWXtZKdsKfkkE_AhIUe_ILg2JVqc8',
    appId: '1:230754350559:ios:a32464c932e439f002c06a',
    messagingSenderId: '230754350559',
    projectId: 'tempus-fcd8f',
    storageBucket: 'tempus-fcd8f.firebasestorage.app',
    iosBundleId: 'com.example.tempus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnqXRWXtZKdsKfkkE_AhIUe_ILg2JVqc8',
    appId: '1:230754350559:ios:a32464c932e439f002c06a',
    messagingSenderId: '230754350559',
    projectId: 'tempus-fcd8f',
    storageBucket: 'tempus-fcd8f.firebasestorage.app',
    iosBundleId: 'com.example.tempus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBy3Omly_AwtJJNhqtLlzQEVWo8uClSU-Y',
    appId: '1:230754350559:web:e9ebc452e8fb805d02c06a',
    messagingSenderId: '230754350559',
    projectId: 'tempus-fcd8f',
    authDomain: 'tempus-fcd8f.firebaseapp.com',
    storageBucket: 'tempus-fcd8f.firebasestorage.app',
  );
}
